<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Tooblox - <?php echo $this->get('_title', 'Untitled') ?></title>
    <meta name="description" content="<?php echo $this->get('_description'); ?>" />
    <meta name="keywords" content="<?php echo $this->get('_keywords'); ?>">
    <meta name="author" content="<?php echo $this->get('_author'); ?>">
    <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="css/main.css" />
    <link rel="shortcut icon" href="../images/icon.png">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <script src="js/main.js"></script>
    <script src="js/tools.js"></script>
    <script>
        var tools = ["<?php echo implode('","', $this->get('tools')); ?>"];
    </script>
</head>
<body>
    <?php include_once("analyticstracking.php"); ?>
    <header>
        <img src="images/icon.png" alt="" class="icon"></img>
        <h1> <a href="/"> Tooblox </a> </h1>
        <ul class="social">
            <li><a href="https://twitter.com/tooblox"><img title="Twitter" alt="Twitter" src="images/social/twitter.png"></a></li>
        </ul>
        <form action="/" method="post">
            <input id="tools" type="text" name="tool" value="" placeholder="Choose your tool" />
            <input type="submit" value="" />
        </form>
    </header>
    <article>
        <div id="error-msg" class="bloc"></div>
