<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Tooblox - <?php echo $this->get('_title', 'Untitled') ?></title>
    <meta name="description" content="<?php echo $this->get('_description'); ?>" />
    <meta name="keywords" content="<?php echo $this->get('_keywords'); ?>">
    <meta name="author" content="<?php echo $this->get('_author'); ?>">
    <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="css/main.css" />
    <link rel="shortcut icon" href="../images/icon.png">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <script src="js/main.js"></script>
    <script src="js/tools.js"></script>
    <script>
        var tools = ["<?php echo implode('","', $this->get('tools')); ?>"];
    </script>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-41791435-1', 'tooblox.com');
        ga('send', 'pageview');
    </script>
</head>
<body>
    <header>
        <img src="images/icon.png" alt="" class="icon" />
        <h1> <a href="/"> Tooblox </a> </h1>
        <ul class="social">
            <li><a href="https://twitter.com/tooblox"><img title="Twitter" alt="Twitter" src="images/social/twitter.png"></a></li>
        </ul>
        <form action="/" method="post">
            <input id="tools" type="text" name="tool" value="" placeholder="Choose your tool" />
            <input type="submit" value="" />
        </form>
    </header>
    <article>
        <div id="error-msg" class="bloc"></div>
