<form class="bloc" action="#">  
	<h1> Tool : Color Picker </h1>
	<p class="center">
    	<label>Click on the box : </label><input id="mycolor" class="color">
    </p>
</form>
<section class="bloc center">
	<p class="inline">
		R <span id="red" class="bloc">100</span>  G <span id="grn" class="bloc">100</span>  B <span id="blu" class="bloc" style="margin-right:50px;">100</span>
		H <span id="hue" class="bloc">100</span>  S <span id="sat" class="bloc">100</span>  V <span id="val" class="bloc">100</span>
	</p>
</section>

<script type="text/javascript" src="js/jscolor/jscolor.js"></script>
<script>
	$(document).ready(function() {
		var color = document.getElementById('mycolor');
		color.addEventListener('change', function() {
			var c_red = this.color.rgb[0] * 100;
			var c_green = this.color.rgb[0] * 100;
			var c_blue = this.color.rgb[2]*100;
			var hue = this.color.hsv[0]* 60;
			var sat = this.color.hsv[1]*100;
			var val = this.color.hsv[2]*100;
			c_red = c_red.toFixed();
			c_green = c_green.toFixed();
			c_blue = c_blue.toFixed();

			$('#red').html("" + Math.round(c_red));
			$('#grn').html("" + Math.round(c_green));
			$('#blu').html("" + Math.round(c_blue));
			$('#hue').html("" + Math.round(hue));
			$('#sat').html("" + Math.round(sat));
			$('#val').html("" + Math.round(val));
		});
	});
</script>