<h1> Welcome in Tooblox </h1>
<p>
Tooblox is a simple website which provide a lot of simple tools. Just enter what you are searching for in the search toolbar and find what you need, or 
click on a direct link below.
</p>
<p>
If you have any tool idea, contact us on <a href="https://twitter.com/tooblox">Twitter</a>.
</p>
<h2>Tools !</h2>
<ul>
<?php foreach($this->get('tools') as $slug => $name): ?>
<li><a href="/<?php echo $slug; ?>"><?php echo $name; ?></a></li>
<?php endforeach; ?>
</ul>
