<form id="random" class="bloc" action="#">
    <h1> Tool : Random</h1>
    <p><label>min</label><input type="text" id="min" /></p>
    <p><label>max</label><input type="text" id="max" /></p>
    <p class="center"><input type="submit" value="Execute" /></p>
</form>
<section class="bloc">
    <h2> Result </h2>
    <span id="result"> </span>
</section>

<script>
    function Random(min, max) {
        console.log(min, max);
        var res = Math.floor(Math.random() * (max - min + 1)) + min;
        return res;
    }
    
    $(document).ready(function() {
        $('#random').submit(function() {
            if (isNumber($('#min').val()) && isNumber($('#max').val()))
            {
                var min = parseInt($('#min').val());
                var max = parseInt($('#max').val());
                if (max > min) {
                    var result = Random(min, max);
                    $('#result').html("" + result);
                    return false;
                }
                else {
                    errorHandler("Something bad happened...")
                }
            }
            else {
                errorHandler("Something bad happened...");
            }
        });
    });
</script>