<form class="block" action="#" id="myform">
	<h1>Tool : Base Converter</h1>
	<p>Just fill one field of the form and click on the convert button.</p><br />
	<p class="inline"><label>Binary</label><input type="text" id="binary" value=""></p>
	<p><label>Decimal</label><input type="text" id="decimal" value=""></p>
	<p><label>Hexadecimal</label><input type="text" id="hexa" value=""></p>
	
</form>

<script>


	function verif_input() {
		if ($('#decimal').val() != '' && !isNumber($('#decimal').val()) &&
			$('#binary').val() != '' && !isNumber($('#binary').val()) &&
			$('#hexa').val() != '' && !isNumber($('#hexa').val()))
			return false;
		return true;
	}

	$('#binary').keyup(function(e) {
		if (e.keyCode == 13) {
			if (verif_input() == false) errorHandler("Something bad happened...");
			else {
				$('#decimal').val(parseInt($('#binary').val(), 2));
				$('#hexa').val(parseInt($('#binary').val(), 2).toString(16).toUpperCase());
			}
		}
	});

	$('#decimal').keyup(function(e) {
		if (e.keyCode == 13) {
			if (verif_input() == false) errorHandler("Something bad happened...");
			else {
				$('#hexa').val(($('#decimal').val() - 0).toString(16).toUpperCase());
				$('#binary').val(($('#decimal').val() - 0).toString(2));
			}
		}
	});

	$('#hexa').keyup(function(e) {
		if (e.keyCode == 13) {
			if (verif_input() == false) errorHandler("Something bad happened...");
			else {
				$('#decimal').val(parseInt($('#hexa').val(), 16));
				$('#binary').val(parseInt($('#hexa').val(), 16).toString(2));
			}
		}
	});

</script>
